### ISSUE TITLE
Typos found in manual

### ISSUE THREAD

**Issue by FreeBASIC-programmer** [phorward/unicc#1]
This is a list of all the typos I found in the unicc manual (dated 21-12-2017).

multiple times: sourcecode => source code
backside first page Responsiblity => Responsibility
page i comiler => compiler
page 3 altought => although
page 3 familar => familiar
page 4 unprecise => imprecise
page 6 paragraph 3 nonterminals-symbols => nonterminal-symbols
page 9 simplyfied => simplified
page 11 multuple => multiple
page 12 recogniziers => recognizers
page 12 interpretered => interpreted
page 13 abount => about
page 13 immediatelly => immediately
page 16 simplyfied => simplified
page 16 overidden => overridden
page 17 familar => familiar
page 17 possibilites => possibilities
page 24 ambigous => ambiguous
page 24 simplyfied => simplified
page 24 substraction => subtraction
page 24 unambigous => unambiguous
page 24 simplyfied => simplified
page 28 comiler => compiler (top)
page 28 comiler => compiler (bottom right)   
page 29 substraction => subtraction
page 30 ambigous => ambiguous
page 30 statet => stated
page 31 todays => today's
page 31 abstact => abstract
page 31 interpretered => interpreted
page 31 Althought => Although
page 36 build-in => built-in
page 36 mulitplication => multiplication
page 36 substract => subtract
page 37 substract => subtract
page 37 numer => number
page 45 substraction => subtraction
page 46 substraction => subtraction
page 46 comparion => comparison
not sure about page 49 convence (line 1)
convence seems wrong but don't know what it is you are trying to convey
page 49 adress => address
page 49 sequencially => sequentially
page 50 fullfill => fulfill
page 50 bracked => bracket
page 51 normaly => normally
page 51 supresses => suppresses
page 51 constructred => constructed
page 61 analsys => analysis
page 68 possibilites => possibilities
page 73 immediatelly => immediately
page 73 interpretered => interpreted
page 73 unprinable => unprintable
page 74 parantheses => parentheses
page 74 familar => familiar
page 75 simultaneausly => simultaneously
page 75 reducton => reduction
page 75 termnals => terminals
page 76 greedyness => greediness
page 77 correclty => correctly
page 78 anomly => anomaly
page 78 ambiguitiy => ambiguity
page 81 wether => whether
page 82 sucesfully => successfully
page 82 if no other production mets => mets is wrong but don't know what you were trying to convey (maybe matches?)
page 82 an nonterminal => a nonterminal
page 83 specify => specify
page 83 refered => referred
page 83 occurence => occurrence
page 89 possibilites => possibilities
page 89 overide => override
page 92 pecedence => precedence
page 93 adoptet => adopted
page 94 predecence => precedence
page 94 beind => behind
page 96 specifiy => specify
page 96 resuling => resulting
page 96 inital => initial
page 98 themself => themselves (not sure)
page 99 ambigous => ambiguous
page 99 supressed => suppressed
page 99 supresses => suppresses
page 100 resynchonization => resynchronization
page 100 resynchonitation => resynchronization
page 101 modifiying => modifying
page 103 syntrax => syntax (three times)
page 103 expressional grammar => expression grammar (not sure)
page 108 accessable => accessible
page 108 refered => referred
page 111 occurence => occurrence (twice)
page 113 refered => referred
page 113 reducting => reduction
page 114 Desciption => Description
page 114 symeteric => symmetric (twice)
page 114 asymeteric => asymmetric
page 115 sytnax => syntax
page 115 recusrively => recursively
page 119 sumbitted => submitted
page 120 occured => occurred
page 121 retrival => retrieval
page 121 invidividual => individual
page 123 submittet => submitted
page 125 inital => initial
page 126 immediatelly => immediately
page 126 specifiy => specify
page 127 comination => combination
page 127 accessable => accessible
page 139 substract => subtract
page 139 Numer => Number
page 151 substraction => subtraction
page 152 substraction => subtraction
page 152 substracting => subtracting
page 152 comparion => comparison

**Comment by phorward** [comment]
wow, thanks for this huge list, I gonna fix it ASAP!

**Comment by phorward** [comment]
I've fixed all your reported typos in the manual, the manpage and the xpl example. Thanks for all these efforts! You can get the updated manual version 1.3.1 from https://phorward.info/download/unicc/unicc.pdf.

May I mention you in the book cover, either by pseudonym or with your real name?

**Comment by FreeBASIC-programmer** [comment]
You may mention me in the book cover. I go by the pseudonym AGS. 
I found some typos in your other project (phorward/phorward)  as well. I'll post the typos there.
The nice thing about typos is that typos are easy to find and easy to fix. Finding (and fixing) 'real' bugs is a lot harder.

**Comment by FreeBASIC-programmer** [comment]
dodo
