### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [phorward/unicc#17]
[An extra null pointer check is not needed in functions](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") like the following.
- [prefix_get_input](https://github.com/phorward/unicc/blob/274d4d658f698e051171d465931e656f837e33ac/targets/C.source/fn.getinput.c#L39 "prefix_get_input function")
- [prefix_parser::get_lexem](https://github.com/phorward/unicc/blob/274d4d658f698e051171d465931e656f837e33ac/targets/C%2B%2B.source/fn.unicode.cpp#L10 "prefix_parser::get_lexem function")

**Comment by phorward** [comment]
Thanks for pointing this out. I was sure that this is not standardized.
I've removed both conditions in 59aa050, maybe there are some more.
The v1.7 release will come together with the next target language, which hopefully is Rust.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/phorward/unicc/commit/59aa050ccbf3f65b1d59f990cdc297982bef7d74 "Deletion of a few unnecessary checks").


>…, maybe there are some more.

Would you like to take another look at remaining update candidates?

* https://github.com/phorward/unicc/blob/274d4d658f698e051171d465931e656f837e33ac/min_lalr1/min_lalr1.c#L759
* https://github.com/phorward/unicc/blob/9f8516c76fb65ac26b6900617ea5aa19ecca1228/parse.c#L1530
* https://github.com/phorward/unicc/blob/274d4d658f698e051171d465931e656f837e33ac/targets/C.source/fn.parse.c#L310
* https://github.com/phorward/unicc/blob/274d4d658f698e051171d465931e656f837e33ac/targets/C.source/fn.stack.c#L27
* https://github.com/phorward/unicc/blob/274d4d658f698e051171d465931e656f837e33ac/targets/C.source/fn.unicode.c#L10
* https://github.com/phorward/unicc/blob/274d4d658f698e051171d465931e656f837e33ac/targets/C%2B%2B.source/fn.getinput.cpp#L39
* https://github.com/phorward/unicc/blob/274d4d658f698e051171d465931e656f837e33ac/targets/C%2B%2B.source/fn.parse.cpp#L279

**Comment by phorward** [comment]
Hi, I've fixed your proposed positions in the code, according to some more with 
c203929. Let me know if you find more.

**Comment by elfring** [comment]
Thanks for [another source code improvement](https://github.com/phorward/unicc/commit/c20392935f224ffbab38c149cdc6dbdaa066ce59 "Refactoring more free()").

-----

Would you eventually like to check by [the software “Coccinelle”](http://coccinelle.lip6.fr/ "Source code transformation with Coccinelle") (also with the help of a variant from the following script) if any interesting update candidates were accidentally left over?

```
@Remove_unnecessary_pointer_checks@
expression x;
@@
-if (\(x != 0 \| x != NULL\))
    free(x);
```

**Comment by phorward** [comment]
OK i can do that right before the 1.7 release currently under development. I'm letting this issue open until then.

**Comment by phorward** [comment]
Will close this now. UniCC will be abandoned.
