### ISSUE TITLE
manpage possibly with wrong name

### ISSUE THREAD

**Issue by maxice8** [phorward/unicc#3]
```
/usr/share/man/man1/unicc.1.1
/usr/share/unicc/README.md
/usr/share/unicc/LICENSE
/usr/share/unicc/unicc.dtd
/usr/share/unicc/targets/python.tlt
/usr/share/unicc/targets/c.tlt
/usr/bin/unicc
```

is unicc.1.1 intentional ? `man unicc` works, and so does `man unicc.1` but i never heard of manpages with name.x.y

**Comment by phorward** [comment]
Thanks, I renamed it to unicc.man locally, resulting in /usr/share/man/man1/unicc.1
